### PR TITLE
Update setup.py install_requires and dependency_links

### PR DESCRIPTION
**Pull request by andeaseme**
to automatically install missing dependencies

### CODE REVIEW

**Comment by thorwhalen** [comment]
@SRHerzog and @valentin-feron , I'll let you code review this one, since I haven't developed in http2py for awhile.

**Comment by thorwhalen** [comment]
@valentin-feron or @SRHerzog , can you look into this?
It seems adding glom and i2 in dependencies should be fine -- but i'm not sure of the 
```
    dependency_links=['git+https://github.com/i2mint/i2.git#egg=i2'],
```
thing.

**Comment by SRHerzog** [comment]
We shouldn't need dependency_links because i2 is on pypi, and that key is to enable setuptools to locate packages in other places.

**Comment by andeaseme** [comment]
> We shouldn't need dependency_links because i2 is on pypi, and that key is to enable setuptools to locate packages in other places.

dependency_links removed. I had trouble pip installing it yesterday but it's working now.

**Comment by andeaseme** [comment]
changes have been added by other commits

**Pull request closed without merging**
